//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Дверь, нуждающаяся в заклинании
/// </summary>
public class DoorNeedingSpell : Door
{
    public DoorNeedingSpell(Room room1, Room room2) : base(room1, room2)
    {
    }
}

