//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Door : MapSite
{
	private object room1;

	private object room2;

	private bool isOpen;

	public Door(Room room1, Room room2)
	{
	}

	public void OtherSideFrom(Room room)
	{
		throw new System.NotImplementedException();
	}

    public override void Enter()
    {
        throw new NotImplementedException();
    }
}

