//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Заколдованная комната
/// </summary>
public class EnchantedRoom : Room
{
	private Spell spell;

	public EnchantedRoom(int roomNo):base(roomNo)
	{
	}

	public EnchantedRoom(int roomNo, Spell spell):base(roomNo)
	{
	}

}

