//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MazeGame
{
	private MazeFactory factory;

	private Maze aMaze;

	private Door aDoor;

	private Room room1;

	private Room room2;

	public IEnumerable<Wall> walls;

	public Maze CreateMaze(MazeFactory factory)
	{
		throw new System.NotImplementedException();
	}

}

