//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MazeFactory
{
	public virtual Door MakeDoor(Room room1, Room room2)
	{
		throw new System.NotImplementedException();
	}

	public virtual Maze MakeMaze()
	{
		throw new System.NotImplementedException();
	}

	public virtual Room MakeRoom(int number)
	{
		throw new System.NotImplementedException();
	}

	public virtual Wall MakeWall()
	{
		throw new System.NotImplementedException();
	}

}

