//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Maze
{
	private Dictionary<int, Room> rooms = null;

	private Room aRoom;

	public Maze()
	{
	}

	public void AddRoom(object room)
	{
		throw new System.NotImplementedException();
	}

	public Room RoomNo(int number)
	{
		throw new System.NotImplementedException();
	}

}

