//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// комната
/// </summary>
public class Room : MapSite
{
	private Dictionary<Direction,MapSite> sides;

	public int RoomNumber
	{
		get;
		private set;
	}

	public Room(int roomNo)
	{
	}

	public MapSite GetSide(Direction direction)
	{
		throw new System.NotImplementedException();
	}

	public void SetSide(Direction direction, MapSite mapSide)
	{
		throw new System.NotImplementedException();
	}

    public override void Enter()
    {
        throw new NotImplementedException();
    }
}

