//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AbctractFactory
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	internal abstract class AbstractBottle
	{
		public abstract void Interact(AbstractWater water);

		public abstract void Interact(AbstractCover cover);

	}
}

