//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AbctractFactory
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	internal class Client
	{
		private AbstractBottle bottle;

		private AbstractFactory factory;

		private AbstractCover cover;

		private AbstractWater water;

		public Client(AbstractFactory factory)
		{
		}

		public void Run()
		{
			throw new System.NotImplementedException();
		}

	}
}

