//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AbctractFactory
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    internal class PepsiBottle : AbstractBottle
    {
        public override void Interact(AbstractCover cover)
        {
            throw new NotImplementedException();
        }

        public override void Interact(AbstractWater water)
        {
            throw new NotImplementedException();
        }
    }
}

