//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Zame0
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Maze
	{
		private Dictionary<int, Room> rooms = null;

		public Maze()
		{
            this.rooms = new Dictionary<int, Room>();
        }

		public void AddRoom(Room room)
		{
            rooms.Add(room.RoomNumber, room);
        }

		public Room RoomNo(int number)
		{
            return rooms[number];
        }

	}
}

