//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Zame0
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class MazeGame
	{
		private Door door;

		private Maze aMaze;

		private Room room2;

		private Room room1;

		public Maze CreateMaze()
		{
            aMaze = new Maze();
            room1 = new Room(1);
            room2 = new Room(2);
            door = new Door(room1, room2);
            aMaze.AddRoom(room1);
            aMaze.AddRoom(room2);

            room1.SetSide(Direction.North, new Wall());
            room1.SetSide(Direction.East, door);
            room1.SetSide(Direction.South, new Wall());
            room1.SetSide(Direction.West, new Wall());

            room2.SetSide(Direction.North, new Wall());
            room2.SetSide(Direction.East, new Wall());
            room2.SetSide(Direction.South, new Wall());
            room2.SetSide(Direction.West, door);
            return aMaze;
        }

	}
}

