//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Zame0
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    /// <summary>
    /// комната
    /// </summary>
    public class Room : MapSite
    {
        public virtual int RoomNumber
        {
            get;
            private set;
        }

        private Dictionary<Direction, MapSite> sides;

        public Room(int roomNo)
        {
            this.RoomNumber = roomNo;
            sides = new Dictionary<Direction, MapSite>(4);
        }

        public MapSite GetSide(Direction direction)
        {
            return sides[direction];
        }

        public void SetSide(Direction direction, MapSite mapSide)
        {
            this.sides.Add(direction, mapSide);
        }

        public override void Enter()
        {
            Console.WriteLine("Room");
        }
    }
}



