//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Products
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Program
	{
		private Client client;

		public static void Main(string[] age)
		{
			throw new System.NotImplementedException();
		}

	}
}

