//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AbctractFactory
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	internal class Client
	{
		private AbstractBottle bottle;

		private AbstractFactory factory;

		private AbstractCover cover;

		private AbstractWater water;

		public Client(AbstractFactory factory)
		{
            water = factory.CreateWater();
            bottle = factory.CreateBottle();
            cover = factory.CreateCover();
        }

		public void Run()
		{
            bottle.Interact(water);
            bottle.Interact(cover);
        }

	}
}

