//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Фабрика для создания комнат с бомбой.
/// </summary>
public class BombedMazeFactory : MazeFactory
{
	/// <summary>
	///  Метод создает комнату с бомбой.
	/// </summary>
	public override Room MakeRoom(int number)
	{
        return new RoomWithBomb(number);
	}

	/// <summary>
	///  Метод создает взорванные стены.
	/// </summary>
	public override Wall MakeWall()
	{
        return new BombedWall();
	}

}

