//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Door : MapSite
{
	private Room room1;

	private Room room2;

	private bool isOpen;

	public Door(Room room1, Room room2)
	{
        this.room1 = room1;
        this.room2 = room2;
    }

	public Room OtherSideFrom(Room room)
	{
        if(room == room1)
            return room2;
        else
            return room1;
    }

    public override void Enter()
    {
        Console.WriteLine("Door");
    }
}

