//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class EnchantedMazeFactory : MazeFactory
{
	public virtual Spell CastSpell()
	{
        return null;
	}
    public override Room MakeRoom(int number)
    {
        return new EnchantedRoom(number, CastSpell());
    }
    public override Door MakeDoor(Room room1, Room room2)
    {
        return new DoorNeedingSpell(room1, room2);
    }

}

