//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MazeGame
{
	private MazeFactory factory;

	private Maze aMaze;

	private Door aDoor;

	private Room room1;

	private Room room2;

	public IEnumerable<Wall> walls;

	public Maze CreateMaze(MazeFactory factory)
	{
        this.factory = factory;
        this.walls = new List<Wall>();
        aMaze = this.factory.MakeMaze();
        room1 = this.factory.MakeRoom(1);
        room2 = this.factory.MakeRoom(2);
        aDoor = this.factory.MakeDoor(room1, room2);
        aMaze.AddRoom(room1);
        aMaze.AddRoom(room2);
        room1.SetSide(Direction.North, this.factory.MakeWall());
        room1.SetSide(Direction.East, aDoor);
        room1.SetSide(Direction.South, this.factory.MakeWall());
        room1.SetSide(Direction.West, this.factory.MakeWall());
        room2.SetSide(Direction.North, this.factory.MakeWall());
        room2.SetSide(Direction.East, this.factory.MakeWall());
        room2.SetSide(Direction.South, this.factory.MakeWall());
        room2.SetSide(Direction.West, aDoor);
        return aMaze;
    }

}

