//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Комната с Бомбой
/// </summary>
public class RoomWithBomb : Room
{
    public RoomWithBomb(int roomNo) : base(roomNo)
    {
    }
}

