//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// комната
/// </summary>
public class Room : MapSite
{
	private Dictionary<Direction,MapSite> sides;
    private Spell spell;
    private int roomNo;

    public Room(int roomNo)
    {
        this.roomNo = roomNo;
        sides = new Dictionary<Direction, MapSite>(4);
    }

    public Room(int roomNo, Spell spell) : this(roomNo)
    {
        this.spell = spell;
    }

    public int RoomNumber
	{
		get { return this.roomNo; }
		private set { roomNo = value; }
	}

    public MapSite GetSide(Direction direction)
	{
        return sides[direction];
    }

	public void SetSide(Direction direction, MapSite mapSide)
	{
        this.sides.Add(direction, mapSide);
    }

    public override void Enter()
    {
        Console.WriteLine("Room");
    }
}

